#!/usr/bin/env python3
"""
Demo script to show the browser open functionality.
This creates a sample HTML file to demonstrate what users will see.
"""

def create_demo_html():
    """Create a demo HTML file to show what the browser open feature generates."""
    
    # Sample Mermaid code
    sample_mermaid = """flowchart TB
    A[User Request] --> B[AI Analysis]
    B --> C[Pattern Matching]
    C --> D[Recommendation]
    D --> E[Diagram Generation]
    E --> F[Display Results]
    
    style A fill:#e1f5fe
    style F fill:#c8e6c9"""
    
    # Create the HTML content using the same template as the app
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Architecture Diagram - Demo</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        
        .header {{
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e0e0e0;
        }}
        
        .header h1 {{
            color: #333;
            margin: 0;
            font-size: 2.5em;
        }}
        
        .header p {{
            color: #666;
            margin: 10px 0 0 0;
            font-size: 1.1em;
        }}
        
        .diagram-container {{
            text-align: center;
            margin: 30px 0;
            padding: 20px;
            background-color: #fafafa;
            border-radius: 8px;
            border: 1px solid #e0e0e0;
        }}
        
        .controls {{
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
        }}
        
        .btn {{
            display: inline-block;
            padding: 10px 20px;
            margin: 0 10px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            border: none;
            cursor: pointer;
            font-size: 14px;
        }}
        
        .btn:hover {{
            background-color: #0056b3;
        }}
        
        .btn-secondary {{
            background-color: #6c757d;
        }}
        
        .btn-secondary:hover {{
            background-color: #545b62;
        }}
        
        .info {{
            background-color: #d1ecf1;
            border: 1px solid #bee5eb;
            color: #0c5460;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏗️ Architecture Diagram</h1>
            <p>Generated by Automated AI Assessment (AAA)</p>
        </div>
        
        <div class="info">
            <strong>🎉 Success!</strong> Your diagram has been opened in a new browser tab. 
            This standalone HTML file contains your complete diagram and can be saved, shared, or printed.
        </div>
        
        <div class="diagram-container">
            <div class="mermaid" id="diagram">
{sample_mermaid}
            </div>
        </div>
        
        <div class="controls">
            <button class="btn" onclick="window.print()">🖨️ Print Diagram</button>
            <button class="btn btn-secondary" onclick="downloadMermaid()">📝 Download Mermaid Code</button>
            <button class="btn btn-secondary" onclick="copyToClipboard()">📋 Copy Code</button>
        </div>
        
        <div class="footer">
            <p>Generated on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>This diagram can be edited at <a href="https://mermaid.live" target="_blank">mermaid.live</a></p>
        </div>
    </div>

    <script>
        // Initialize Mermaid
        mermaid.initialize({{ 
            startOnLoad: true,
            theme: 'default',
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true
            }}
        }});
        
        // Download Mermaid code
        function downloadMermaid() {{
            const mermaidCode = `{sample_mermaid}`;
            const blob = new Blob([mermaidCode], {{ type: 'text/plain' }});
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'diagram.mmd';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }}
        
        // Copy to clipboard
        function copyToClipboard() {{
            const mermaidCode = `{sample_mermaid}`;
            navigator.clipboard.writeText(mermaidCode).then(function() {{
                alert('Mermaid code copied to clipboard!');
            }}, function(err) {{
                console.error('Could not copy text: ', err);
                // Fallback for older browsers
                const textArea = document.createElement('textarea');
                textArea.value = mermaidCode;
                document.body.appendChild(textArea);
                textArea.select();
                document.execCommand('copy');
                document.body.removeChild(textArea);
                alert('Mermaid code copied to clipboard!');
            }});
        }}
        
        // Show success message
        console.log('✅ Diagram loaded successfully in browser tab!');
    </script>
</body>
</html>"""
    
    # Save the demo file
    import os
    os.makedirs("exports", exist_ok=True)
    demo_path = "exports/demo_browser_open.html"
    
    with open(demo_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    return demo_path, html_content

def main():
    """Create and show demo of browser open functionality."""
    print("Creating Browser Open Demo...")
    print("=" * 50)
    
    try:
        demo_path, html_content = create_demo_html()
        
        print(f"✅ Demo HTML file created: {demo_path}")
        print(f"📄 File size: {len(html_content):,} characters")
        print(f"📁 Full path: {os.path.abspath(demo_path)}")
        
        print("\n🌐 What happens when users click 'Open in Browser':")
        print("1. HTML file is generated with the diagram")
        print("2. File is saved to exports/ directory")
        print("3. JavaScript automatically opens new browser tab")
        print("4. User sees a standalone, interactive diagram page")
        print("5. Page includes print, download, and copy features")
        
        print("\n📋 Features in the browser page:")
        print("- 🖨️ Print button for hard copies")
        print("- 📝 Download Mermaid code as .mmd file")
        print("- 📋 Copy code to clipboard")
        print("- 🎨 Clean, professional styling")
        print("- 📱 Mobile-responsive design")
        print("- 🔗 Link to mermaid.live for editing")
        
        print(f"\n💡 To see the demo, open: {demo_path}")
        print("   Or run: open exports/demo_browser_open.html")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to create demo: {e}")
        return False

if __name__ == "__main__":
    import os
    main()