version: '3.8'

# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  api:
    build:
      context: .
      args:
        SKIP_TESTS: "true"
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - LOGGING_LEVEL=INFO
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
  ui:
    build:
      context: .
      args:
        SKIP_TESTS: "true"
    environment:
      - PYTHONPATH=/app
      - API_BASE_URL=http://api:8000
      - LOGGING_LEVEL=INFO
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - api
      - ui
    restart: unless-stopped
    profiles:
      - nginx