version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
      - ./cache:/app/cache
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    
  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    environment:
      - PYTHONPATH=/app
    command: streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: