api:
  cors_origins:
  - '*'
  docs_url: /docs
  enable_cors: true
  enable_docs: false
  host: 0.0.0.0
  max_request_size: 10485760
  port: 8000
  redoc_url: /redoc
  timeout_seconds: 30
  workers: 1
cache:
  backend: redis
  cleanup_interval_seconds: 300
  default_ttl_seconds: 3600
  max_size_mb: 100
  redis_config: null
custom: {}
database:
  echo: false
  max_overflow: 20
  pool_recycle: 3600
  pool_size: 10
  pool_timeout: 30
  url: postgresql://user:pass@prod-db:5432/aaa
debug: false
environment: production
logging:
  backtrace: true
  compression: gz
  diagnose: true
  file_path: logs/aaa-prod.log
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}'
  level: WARNING
  retention: 30 days
  rotation: 1 day
  serialize: false
monitoring:
  alert_webhook_url: https://alerts.company.com/webhook
  check_interval_seconds: 30
  enable_profiling: false
  enabled: true
  export_interval_seconds: 300
  health_check_port: 8080
  metrics_port: 9090
  profiling_sample_rate: 0.01
  retention_days: 30
redis:
  db: 0
  host: prod-redis
  max_connections: 50
  password: null
  port: 6379
  socket_connect_timeout: 30
  socket_timeout: 30
  ssl: false
security:
  enable_rate_limiting: true
  jwt_algorithm: HS256
  jwt_expiration_hours: 24
  lockout_duration_minutes: 15
  max_login_attempts: 5
  password_min_length: 8
  rate_limit_per_hour: 1000
  rate_limit_per_minute: 60
  secret_key: CHANGE-THIS-IN-PRODUCTION
system:
  autonomy:
    autonomy_boost_multiplier: 1.1
    confidence_boost_factor: 1.2
    decision_independence_weight: 0.25
    exception_handling_weight: 0.2
    fully_automatable_threshold: 0.8
    high_autonomy_boost_threshold: 0.7
    learning_adaptation_weight: 0.15
    min_autonomy_threshold: 0.7
    partially_automatable_threshold: 0.6
    reasoning_capability_weight: 0.3
    self_monitoring_weight: 0.1
    # Agentic necessity assessment thresholds
    agentic_necessity_threshold: 0.6
    traditional_suitability_threshold: 0.7
    hybrid_zone_threshold: 0.1
  llm_generation:
    api_request_timeout: 30.0
    frequency_penalty: 0.0
    http_timeout: 10
    llm_timeout: 20
    max_tokens: 1000
    presence_penalty: 0.0
    temperature: 0.3
    top_p: 1.0
  pattern_matching:
    autonomy_level_weight: 0.4
    confidence_weight: 0.2
    decision_independence_weight: 0.2
    excellent_fit_threshold: 0.8
    exception_handling_weight: 0.1
    good_fit_threshold: 0.6
    high_similarity_threshold: 0.7
    learning_potential_weight: 0.05
    moderate_similarity_threshold: 0.4
    moderate_tag_match_threshold: 0.4
    reasoning_capability_weight: 0.25
    strong_tag_match_threshold: 0.7
    tag_weight: 0.3
    vector_weight: 0.5
  recommendations:
    autonomy_boost_factor: 0.2
    conceptual_similarity_threshold: 0.7
    min_recommendation_confidence: 0.7
    multi_agent_boost: 0.1
    new_pattern_creation_threshold: 0.7
    pattern_enhancement_similarity_threshold: 0.7
    reasoning_boost_amount: 0.1
    reasoning_boost_threshold: 3
    tech_stack_inclusion_threshold: 0.6
ui:
  enable_debug: false
  host: 0.0.0.0
  port: 8501
  sidebar_state: expanded
  theme: light
  title: Automated AI Assessment (AAA)
  wide_mode: true
